version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile.dev

    command: npx nest start server --watch

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev

    command: npx next dev apps/web

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
