services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile.dev

    command: npx nest start server --watch

    environment:
      - NODE_ENV=development

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/web/node_modules
