@startuml
' Combined Domain Model
' Generated: 2025-12-02T15:03:01.006Z
' Modules: auth, calculation-parameters, classes, courses, rooms, shifts, users


class User {
    +id: number
    +name: string
    +email: string
    -password: string
    +role: string
    +phone: string
    +createdAt: Date
    +setPassword(hashedPassword: string): void
    +getPassword(): string
}
class RefreshToken {
    +id: number
    +tokenHash: string
    +user: User
    +expiresAt: number
    +createdAt: Date
    +revoked: boolean
}
class CalculationParameters {
    +id: number
    +dropoutPercentage: number
    +studentsPerSmallRoom: number
    +studentsPerMediumRoom: number
    +studentsPerBigRoom: number
}
class Course {
    +id: number
    +name: string
    +knowledgeArea: string
    +vacancies: number
    +periodQuantities: number
    +openingYear: number
    +numberOfSemesters: number
    +classes: Class[]
}
class Shift {
    +id: number
    +name: string
    +classes: Class[]
}
class Class {
    +id: number
    +courseId: number
    +course: Course
    +shiftId: number
    +shift: Shift
    +year: number
    +semester: number
    +currentStudents: number
    +isAssumed?: boolean
}
class Rooms {
    +id: number
    +block: string
    +number: number
    +size: string
    +courseId: number
    +course: Course
    +classId: number
    +class: Class
}

' Relationships
RefreshToken "*" }o-- "1" User
Class "*" }o-- "1" Course
Class "*" }o-- "1" Shift
Rooms "*" }o-- "1" Course
Rooms "*" }o-- "1" Class
@enduml
