@startuml
' Combined Domain Model
' Generated: 2025-11-19T23:57:09.324Z
' Modules: calculation-parameters, classes, courses, rooms, shifts, users


class CalculationParameters {
    +id: number
    +dropoutPercentage: number
    +studentsPerSmallRoom: number
    +studentsPerMediumRoom: number
    +studentsPerBigRoom: number
}
class Course {
    +id: number
    +name: string
    +knowledgeArea: string
    +vacancies: number
    +periodQuantities: number
    +openingYear: number
    +classes: Class[]
}
class Shift {
    +id: number
    +name: string
    +classes: Class[]
}
class Class {
    +id: number
    +courseId: number
    +course: Course
    +shiftId: number
    +shift: Shift
    +year: number
    +semester: number
    +currentStudents: number
}
class Rooms {
    +id: number
    +block: string
    +number: number
    +size: string
}
class User {
    +id: number
    +name: string
    +email: string
    -password: string
    +role: string
    +phone: string
    +createdAt: Date
    +setPassword(hashedPassword: string): void
    +getPassword(): string
}

' Relationships
Class "*" }o-- "1" Course
Class "*" }o-- "1" Shift
@enduml
