@startuml
class Course {
    +id: number
    +name: string
    +knowledgeArea: string
    +announcement: number
    +status: string
    +expectedStudents: number
    +classes: Class[]
}
class Shift {
    +id: number
    +name: string
    +classes: Class[]
}
class Class {
    +id: number
    +courseId: number
    +course: Course
    +shiftId: number
    +shift: Shift
    +year: number
    +semester: number
    +currentStudents: number
}

' Relationships
Class "*" }o-- "1" Course
Class "*" }o-- "1" Shift
@enduml
